### ISSUE TITLE
Strange cache-loader error

### ISSUE THREAD

**Issue by waxlamp** [pksunkara/vue-builder-webpack-plugin#22]
Hi! Great project!

I'm currently running into an error when trying to use folder mode: I get this message

```
      var mtime = stats.mtime.getTime();
                              ^

TypeError: stats.mtime.getTime is not a function
    at /home/roni/work/roi-thumbnail/node_modules/cache-loader/dist/index.js:72:31
    at process.nextTick (/home/roni/work/roi-thumbnail/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
error Command failed with exit code 1.
```

I am not sure where this is originating. Any ideas?

**Comment by waxlamp** [comment]
I have a bit more insight here: this seems to happen when I drop an empty `MyComponent.vue.css` file next to the others. This then causes the error whether in folder mode or not, but folder mode doesn't detect a component within a folder unless all three files (template, script, style) are present. I believe that's a separate issue and will open a new one for that.

**Comment by waxlamp** [comment]
More digging... the problem occurs on the generated .vue file itself, when the cache-loader module attempts to figure out if that file has been updated. I assume because it's a virtual file, that's causing a problem with the `stat()` call.

Unfortunately this is a showstopper for me so I'll have to find a different way to break my files out of my components :disappointed:

Let me know if there's some way I can help fix the problems (or if I may be doing something wrong to cause the problems). Thanks!

**Comment by waxlamp** [comment]
Ah I believe it is the watch mode from vue-cli that's causing the problem: https://github.com/rmarscher/virtual-module-webpack-plugin/issues/6.

Any idea on getting around this?

Sorry for all the comments!
